version: '1'
services:
  postgres:
    image: postgres:latest
    container_name: ex_13_1_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
  redis:
    image: redis:alpine
    container_name: ex_13_1_redis
    ports:
      - "${REDIS_PORT}:6379"
networks:
  network1:
    external: true